name: fastapi1
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anyio=3.3.2=py37hf985489_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.2=py37hf985489_1
  - argon2-cffi=20.1.0=py37h271585c_2
  - asgiref=3.4.1=pyhd8ed1ab_0
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - audioread=2.1.9=py37hf985489_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd8ed1ab_0
  - bottleneck=1.3.2=py37hf1fa96c_1
  - brotlipy=0.7.0=py37h271585c_1001
  - bzip2=1.0.8=h0d85af4_4
  - ca-certificates=2021.10.8=h033912b_0
  - certifi=2021.10.8=py37hf985489_0
  - cffi=1.14.6=py37hda351d9_0
  - chardet=4.0.0=py37hf985489_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=8.0.2=py37hf985489_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.4.7=py37hce4a858_0
  - cycler=0.10.0=py_2
  - decorator=5.1.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.2=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - fastapi=0.70.0=pyhd8ed1ab_0
  - ffmpeg=4.3.2=h4dad6da_0
  - freetype=2.10.4=h4cff582_1
  - gettext=0.19.8.1=h7937167_1005
  - gmp=6.2.1=h2e338ed_0
  - gnutls=3.6.13=h756fd2b_1
  - h11=0.12.0=pyhd8ed1ab_0
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.8.1=py37hf985489_0
  - intel-openmp=2021.3.0=hecd8cb5_3375
  - ipykernel=5.5.5=py37h85f7c60_0
  - ipython=7.28.0=py37h4c52d7d_0
  - ipython_genutils=0.2.0=py_1
  - jbig=2.1=h0d85af4_2003
  - jedi=0.18.0=py37hf985489_2
  - jinja2=3.0.2=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9d=hbcb3906_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.1.0=pyhd8ed1ab_0
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_core=4.8.1=py37hf985489_0
  - jupyter_server=1.11.1=pyhd8ed1ab_0
  - jupyterlab=3.1.18=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.8.2=pyhd8ed1ab_0
  - kiwisolver=1.3.2=py37h737db71_0
  - lame=3.100=h35c211d_1001
  - lcms2=2.12=h577c468_0
  - lerc=2.2.1=h046ec9c_0
  - libcxx=12.0.0=h2f01273_0
  - libdeflate=1.7=h35c211d_5
  - libffi=3.3=hb1e8313_2
  - libflac=1.3.3=h046ec9c_1
  - libgfortran=3.0.1=0
  - libiconv=1.16=haf1e3a3_0
  - libllvm11=11.1.0=hd011deb_2
  - libogg=1.3.4=h35c211d_1
  - libopus=1.3.1=hc929b4f_1
  - libpng=1.6.37=h7cec526_2
  - librosa=0.8.1=pyhd8ed1ab_0
  - libsndfile=1.0.31=he49afe7_1
  - libsodium=1.0.18=hbcb3906_1
  - libtiff=4.3.0=h1167814_1
  - libvorbis=1.3.7=h046ec9c_0
  - libwebp-base=1.2.1=h0d85af4_0
  - llvm-openmp=12.0.1=hda6cdc1_1
  - llvmlite=0.37.0=py37h62ea057_0
  - lz4-c=1.9.3=he49afe7_1
  - markupsafe=2.0.1=py37h271585c_0
  - matplotlib-base=3.4.3=py37h3147e9e_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py37h271585c_1004
  - mkl=2021.3.0=hecd8cb5_517
  - mkl-service=2.4.0=py37h9ed2024_0
  - mkl_fft=1.3.0=py37h4a7008c_2
  - mkl_random=1.2.2=py37hb2f4e1b_0
  - natsort=7.1.1=pyhd3eb1b0_0
  - nbclassic=0.3.2=pyhd8ed1ab_0
  - nbclient=0.5.4=pyhd8ed1ab_0
  - nbconvert=6.2.0=py37hf985489_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h0a44026_1
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - nettle=3.6=hedd7734_0
  - notebook=6.4.4=pyha770c72_0
  - numba=0.54.1=py37h078fc1e_0
  - numexpr=2.7.3=py37h5873af2_1
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=hfd3ada9_0
  - openjpeg=2.4.0=h6e7aa92_1
  - openssl=1.1.1l=h0d85af4_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.3=py37h5008ddb_0
  - pandoc=2.14.2=h0d85af4_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.2=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.2=py37h76dc067_0
  - pip=21.0.1=py37hecd8cb5_0
  - pooch=1.5.1=pyhd8ed1ab_0
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.20=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pydantic=1.8.2=py37h271585c_0
  - pydub=0.25.1=pyhd8ed1ab_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py37h271585c_2
  - pysocks=1.7.1=py37hf985489_3
  - pysoundfile=0.10.3.post1=pyhd3deb0d_0
  - python=3.7.11=h88f2d9e_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-multipart=0.0.5=py_0
  - python_abi=3.7=2_cp37m
  - pytz=2021.3=pyhd3eb1b0_0
  - pyzmq=22.3.0=py37h8f778e5_0
  - readline=8.1=h9ed2024_0
  - requests=2.26.0=pyhd8ed1ab_0
  - requests-unixsocket=0.2.0=py_0
  - resampy=0.2.2=py_0
  - scikit-learn=0.24.2=py37hb2f4e1b_0
  - scipy=1.7.1=py37h88652d9_2
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=58.0.4=py37hecd8cb5_0
  - sniffio=1.2.0=py37hf985489_1
  - sqlite=3.36.0=hce871da_0
  - starlette=0.16.0=pyhd8ed1ab_0
  - terminado=0.12.1=py37hf985489_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=3.0.0=pyh8a188c0_0
  - tk=8.6.11=h7bc2e8c_0
  - tornado=6.1=py37h271585c_1
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.1.0=pyhd8ed1ab_0
  - urllib3=1.26.7=pyhd8ed1ab_0
  - uvicorn=0.15.0=py37hf985489_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=0.57.0=py37hf985489_4
  - wheel=0.37.0=pyhd3eb1b0_1
  - x264=1!161.3030=h0d85af4_1
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.4=he49afe7_1
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.5.0=h582d3a0_0
  - pip:
    - absl-py==0.14.1
    - astunparse==1.6.3
    - cachetools==4.2.4
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - keras==2.4.1
    - keras-preprocessing==1.1.2
    - markdown==3.3.4
    - numpy==1.19.5
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - protobuf==3.18.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-speech-features==0.6
    - pyyaml==5.4.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - six==1.15.0
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.4.1
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - typing-extensions==3.7.4.3
    - werkzeug==2.0.2
    - wrapt==1.12.1
prefix: /Users/lsaetta/opt/anaconda3/envs/fastapi1
